# コントローラーなどで扱うステータスなど
ACCOUNT_STATUS_INACTIVE = 1
MAIN_IMAGE_SELECTED = 1
SUB_IMAGE_FIRST_SELECTED = 1
SUB_IMAGE_SECOND_SELECTED = 1

# 最大表示数関連
POSTS_PER_PAGE = 24
MAXIMUM_AUTOCOMPLATE = 10
MAXIMUM_VIEW_HISTORY = 50
MAXIMUM_TAG = 21
MAXIMUM_COMMENT = 3
SMAXIMUM_TOPPAGE_POST = 8
REFERENCE_TAG = 5
INITIAL_COMMENT_MAX = 4

# google map api関連
TOKYO_LATITUDE = 35.6803997
TOKYO_LONGITUDE = 139.7690174
GOOGLE_MAP_RADIUS = 2500
NO_STORE_HIT = 0
